### ISSUE TITLE
RadeonProRenderSDK: shader compilation error with rocm 6.1.3

### ISSUE THREAD

**Issue by feniksa** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#688]
## Issue
Blender rendering on GPU doesn't work with rocm 6.1.3

## System Setup (Environment)
Ubuntu 22.04.4 LTS
AMD Radeon RX 6800 XT, AMD Ryzen Threadripper 3960X 24-Core Processor, rocm 6.1.3
Blender 4.1.1
GPU rendering

## Detailed Description
RPR context initialization for Northstar gives -4 error, RPR_ERROR_SHADER_COMPILATION .

Looks like shaders for rocm 6.1.3 has some difference compare to rocm 5.7.3 .

For now, ubuntu amdgpu drivers uses rocm 6.1.3 .

Possible solutions of this issue:
Short-term solution: Add pre-compiled shaders for rocm 6.1.3
Long-term solution: Add fallback mechanism to compile shaders on specific machine (fallback mode).
It is always cat and mouse game to add pre-compiled shaders for new GPU's, for new ROCM version and MAYbe for different platfroms.

**Comment by feniksa** [comment]
@takahiroharada 

Maybe, this issue should go to RPR repo, not for blender.
