### ISSUE TITLE
3.X crashes at activation on macOS 10.13

### ISSUE THREAD

**Issue by benjamindahl** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#353]
I downloaded the addon and tried to install it from inside blender.

Hardware: 
mac mini (late 2012), 2.3 GHz Core i7, 16GB DDR3 Memory
eGPU: AMD Radeon RX 580

Software:
macOS 10.13.6 (High Sierra)
Blender 2.93.4
RadeonProRender-Plugin 3.0.8 as well as 3.2.2

Blender crashes, when plugin is being activated with following error

`2021-09-08 10:49:19,513 INFO rpr.default [140736194306944]:  rprsdk_bin_path: /Users/molitor/Library/Application Support/Blender/2.93/scripts/addons/rprblender
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/molitor/Library/Application Support/Blender/2.93/scripts/addons/rprblender/libTahoe64.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/molitor/Library/Application Support/Blender/2.93/scripts/addons/rprblender/libTahoe64.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

/usr/local/bin/blender: line 2: 82371 Killed: 9               '/Applications/Blender.app/Contents/MacOS/Blender' "$@"`

**Comment by benjamindahl** [comment]
Latest test working version of the Plugin 2.5.1

**Comment by bsavery** [comment]
We no longer support High Sierra.  Sorry.  There should be older builds that are usable as you noted.

**Comment by benjamindahl** [comment]
Ok, but would be nice if you wrote it on the download page, that it requires a higher version of macOS. 
Would have saved me quite some time.

Can you explain how the build process would work on macOS? Maybe I can build it from the source code for my specific OS

Cheers
Benny

**Comment by benjamindahl** [comment]
BTW:
you tell people here, that it should work with 10.13. 
What is actually true?
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/README-OSX.md
